server:
  port: 8082

spring:
  application:
    name: message-service
  data:
    mongodb:
      uri: ${MESSAGE_MONGODB_URL:mongodb+srv://doannhb:ga7eNC.VDeARB5Q@cluster0.krzv10n.mongodb.net/arena_message_service?retryWrites=true&w=majority}
      database: ${MESSAGE_MONGODB_DATABASE:arena_message_db}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.arenaaxis.messageservice: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

match:
  limit: 10 # in days

service:
  user:
    url: ${USER_SERVICE_URL:http://www.executexan.store}
  order:
    url: ${ORDER_SERVICE_URL:http://www.executexan.store/api/v1}